---
- name: Installation of Docker on Lab Azure
  hosts: all
  become: yes
  tasks:
    - name: Install dnf-plugins-core
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add depot Docker CE
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE and Docker Compose
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        allowerasing: yes

    - name: Run docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: add user to docker group
      user:
        name: sysadmin
        groups: docker
        append: yes
